vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /public/images
           upload_destination: '%kernel.project_dir%/public/public/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
